import React, { useState, useEffect, useRef } from 'react'
import { X, Copy, Download, Mail, PenTool, CheckCircle2 } from 'lucide-react'
import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'

export default function NarrativeReport({ loading, narrative, chartCount, onClose }) {
    const [displayedText, setDisplayedText] = useState('')
    const [isTyping, setIsTyping] = useState(false)
    const [copiedContent, setCopiedContent] = useState(null)
    const reportRef = useRef(null)

    // Typewriter effect
    useEffect(() => {
        if (!loading && narrative) {
            setIsTyping(true)
            setDisplayedText('')
            let i = 0
            const timer = setInterval(() => {
                setDisplayedText(narrative.slice(0, i))
                i++
                if (i > narrative.length) {
                    clearInterval(timer)
                    setIsTyping(false)
                }
            }, 10)
            return () => clearInterval(timer)
        }
    }, [loading, narrative])

    const handleCopy = () => {
        navigator.clipboard.writeText(narrative)
        setCopiedContent('copy')
        setTimeout(() => setCopiedContent(null), 2000)
    }

    const handleEmail = () => {
        const date = new Date().toLocaleDateString()
        const text = `Subject: BI Report — ${date}\n\n${narrative}\n\nGenerated by NeuralBI`
        navigator.clipboard.writeText(text)
        setCopiedContent('email')
        setTimeout(() => setCopiedContent(null), 2000)
    }

    const handlePdf = async () => {
        if (!reportRef.current) return
        setCopiedContent('pdf_loading')
        try {
            const canvas = await html2canvas(reportRef.current, {
                backgroundColor: '#050811',
                scale: 1.5,
            })
            const imgData = canvas.toDataURL('image/png')
            const pdf = new jsPDF('p', 'mm', 'a4')
            const pdfWidth = pdf.internal.pageSize.getWidth()
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
            pdf.save(`NeuralBI_Report_${new Date().toISOString().split('T')[0]}.pdf`)

            setCopiedContent('pdf_done')
            setTimeout(() => setCopiedContent(null), 2000)
        } catch (e) {
            console.error(e)
            setCopiedContent(null)
        }
    }

    return (
        <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            background: 'rgba(5, 8, 17, 0.95)',
            backdropFilter: 'blur(20px)',
            zIndex: 1000,
            display: 'flex', justifyContent: 'center', alignItems: 'flex-start',
            overflowY: 'auto', padding: '40px 20px'
        }}>
            {loading ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'white' }}>
                    <div style={{ fontSize: '48px', animation: 'pulseObj 1.5s infinite', marginBottom: '24px' }}>✍️</div>
                    <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', fontWeight: 600, marginBottom: '8px' }}>
                        Writing your executive report...
                    </h2>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '15px' }}>
                        Analyzing {chartCount} visualizations
                    </p>
                    <div style={{ marginTop: '30px', width: '200px', height: '4px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', overflow: 'hidden' }}>
                        <div style={{ width: '50%', height: '100%', background: 'linear-gradient(90deg, var(--accent-primary), var(--accent-cyan))', animation: 'loadingBar 1.5s infinite ease-in-out' }} />
                    </div>
                </div>
            ) : (
                <div className="glass-card" style={{ width: '100%', maxWidth: '760px', padding: '48px', position: 'relative' }}>
                    {/* Top Bar */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                            <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'linear-gradient(135deg, var(--accent-primary), var(--accent-cyan))' }} />
                            <span style={{ fontSize: '16px', fontWeight: 600, color: 'var(--text-primary)' }}>Executive Report</span>
                        </div>
                        <button onClick={onClose} className="btn-ghost" style={{ padding: '8px' }}>
                            <X size={20} />
                        </button>
                    </div>

                    {/* Report Metadata Row */}
                    <div style={{ display: 'flex', gap: '12px', marginBottom: '32px', flexWrap: 'wrap' }}>
                        <span style={{ fontSize: '12px', background: 'rgba(255,255,255,0.05)', padding: '6px 14px', borderRadius: '16px', color: 'var(--text-muted)' }}>
                            📅 {new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        </span>
                        <span style={{ fontSize: '12px', background: 'rgba(255,255,255,0.05)', padding: '6px 14px', borderRadius: '16px', color: 'var(--text-muted)' }}>
                            📊 Based on {chartCount} analyses
                        </span>
                        <span style={{ fontSize: '12px', background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.2)', padding: '6px 14px', borderRadius: '16px', color: 'var(--accent-primary)' }}>
                            ✍️ AI-Generated Summary
                        </span>
                    </div>

                    {/* Divider */}
                    <div style={{ height: '1px', background: 'linear-gradient(90deg, transparent, var(--accent-primary), var(--accent-cyan), transparent)', marginBottom: '40px', opacity: 0.5 }} />

                    {/* Narrative Content to render as PDF */}
                    <div ref={reportRef} style={{ background: '#050811', padding: '20px', borderRadius: '12px' }}>
                        <h1 style={{ fontFamily: 'var(--font-heading)', fontSize: '28px', fontWeight: 700, margin: '0 0 32px 0', background: 'linear-gradient(90deg, var(--text-primary), var(--text-secondary))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                            Business Intelligence Report
                        </h1>

                        <div style={{
                            fontFamily: "'Inter', sans-serif", fontSize: '16px', lineHeight: 1.8,
                            color: 'var(--text-primary)', whiteSpace: 'pre-wrap'
                        }}>
                            {displayedText.split('\n\n').map((paragraph, idx) => {
                                if (!paragraph.trim()) return null;
                                return (
                                    <p key={idx} style={{ marginBottom: '20px' }}>
                                        {idx === 0 && paragraph.length > 0 ? (
                                            <>
                                                <span style={{
                                                    float: 'left', fontSize: '48px', lineHeight: '40px',
                                                    paddingTop: '8px', paddingRight: '8px',
                                                    color: 'var(--accent-cyan)', fontWeight: 700,
                                                    fontFamily: 'var(--font-heading)'
                                                }}>{paragraph.charAt(0)}</span>
                                                {paragraph.slice(1)}
                                            </>
                                        ) : paragraph}
                                    </p>
                                )
                            })}
                        </div>
                    </div>

                    {/* Action Buttons Row */}
                    {!isTyping && (
                        <div style={{ display: 'flex', gap: '12px', marginTop: '48px', flexWrap: 'wrap', borderTop: '1px solid var(--glass-border)', paddingTop: '24px' }}>
                            <button onClick={handleCopy} className="btn-ghost" style={{ background: 'rgba(255,255,255,0.05)' }}>
                                {copiedContent === 'copy' ? <><CheckCircle2 size={16} color="var(--accent-green)" /> Copied!</> : <><Copy size={16} /> Copy to Clipboard</>}
                            </button>
                            <button onClick={handlePdf} className="btn-ghost" style={{ background: 'rgba(255,255,255,0.05)' }} disabled={copiedContent === 'pdf_loading'}>
                                {copiedContent === 'pdf_loading' ? <><span style={{ animation: 'spin 2s linear infinite' }}>⏳</span> Generating PDF...</> : copiedContent === 'pdf_done' ? <><CheckCircle2 size={16} color="var(--accent-green)" /> Downloaded!</> : <><Download size={16} /> Download as PDF</>}
                            </button>
                            <button onClick={handleEmail} className="btn-ghost" style={{ background: 'rgba(255,255,255,0.05)' }}>
                                {copiedContent === 'email' ? <><CheckCircle2 size={16} color="var(--accent-green)" /> Ready to paste!</> : <><Mail size={16} /> Copy as Email</>}
                            </button>
                        </div>
                    )}
                </div>
            )}
            <style>{`
                @keyframes pulseObj { 0% { transform: scale(1); } 50% { transform: scale(1.1); } 100% { transform: scale(1); } }
                @keyframes loadingBar { 0% { transform: translateX(-100%); } 100% { transform: translateX(200%); } }
                @keyframes spin { 100% { transform: rotate(360deg); } }
            `}</style>
        </div>
    )
}
